CREATE SEQUENCE USER_ACCOUNT_SEQ;

CREATE TABLE USER_ACCOUNT
(
    id        INTEGER PRIMARY KEY,
    username  VARCHAR(50)  NOT NULL UNIQUE,
    password  VARCHAR(50)  NOT NULL,
    email     VARCHAR(50)  NOT NULL UNIQUE,
    phone     VARCHAR(50)  NOT NULL UNIQUE,
    address   VARCHAR(100) NOT NULL,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL
);